GET  http://localhost:5000/api/files
      ?parent=6012ffaf30cc6f2748a7b4f7
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMTE1ZmRlOTk1MDljMjgxMDA5NzdiZSIsImlhdCI6MTYxMTg1Nzc4NywiZXhwIjoxNjExODYxMzg3fQ.bi-lKzYqGDLj0BaeU1h-wbbQgXW1kOUO2ew_UR3s910
